import React from 'react';
import { Photo, Service } from './types';

export const COLORS = {
  primary: '#ff00ff', // Neon Magenta
  secondary: '#00ffff', // Electric Blue
  accent: '#7000ff', // Deep Purple
  bg: '#050505',
};

export const TRANSLATIONS = {
  pt: {
    nav: { home: 'HOME', about: 'SOBRE', academic: 'FORMAÇÃO', experience: 'EXPERIÊNCIA', socials: 'SOCIAL', portfolio: 'PORTFÓLIO', services: 'SERVIÇOS', contact: 'CONTATO' },
    hero: {
      tagline: 'picMi Photography Experience',
      title1: 'Imagem é',
      titleAccent: 'comunicação',
      desc: 'Transmite e traduz sentimentos. Vamos juntos traduzir pro mundo o seu projeto ou evento!',
      btnPortfolio: 'EXPLORAR PORTFÓLIO',
      btnAbout: 'QUEM SOU',
      btnExperience: 'EXPERIÊNCIA CORPORATIVA',
      btnAcademic: 'FORMAÇÃO ACADÊMICA',
      btnContact: 'ENTRE EM CONTATO',
      btnSocials: 'REDES SOCIAIS',
      btnWork: 'EXPLORAR TRABALHOS',
      btnQuote: 'SOLICITAR ORÇAMENTO'
    },
    about: {
      tag: 'QUEM SOU',
      title: 'Millena Almeida',
      p1: 'Millena Almeida Santos, 26 anos, nascida em 18/09/1999, na cidade de São Paulo. Criada na periferia de São Paulo, na região do Campo Limpo/Capão Redondo, onde ainda resido. Desde criança, tenho uma conexão e manifestação artística notável, especialmente com o cinema e a musicas, que sempre fizeram parte da minha vida e consumo cultural fortemente.',
      p2: 'Possuo facilidade na oratória e escrita, essenciais para a escrita de roteiros de trabalhos artísticos e na comunicação diária que o meio de produção exige. Acredito que os melhores projetos se constroem com uma comunicação transparente entre o cliente e eu, para que o resultado final agrade 100% a todos.',
      p3: 'Trabalho com respeito, criatividade, ousadia, inteligente, potência e comprometimento. Busco impactar o cenário audiovisual brasileiro, engrandecendo nossa cultura local. Utilizo a Fotografia para transmitir sentimentos e causas, traduzindo o intraduzível.',
      projects: 'Projetos',
      creativity: 'Creativity'
    },
    academic: {
      tag: 'LEVEL UP',
      title: 'Formação Acadêmica',
      close: 'X',
      statusTitle: 'STATUS_DO_SISTEMA: DADOS_ACADEMICOS',
      fullContent: 'Formada em Fotografia pela EBAC – Escola Britânica de Artes Criativas e Tecnologia, além de possuir outros cursos decisivos na área, como: Diretor de Fotografia – Um Contador de Histórias Visuais, mestrado por Adrian Teijido, conhecido principalmente por sua direção em fotografia no filme ganhador do Oscar: Ainda estou aqui. Também possuo bacharel em Serviço Social, pela Faculdade Metropolitanas Unidas – FMU, unidade Liberdade.\n\nInglês Fluente (formada pela CNA).',
      item1Title: 'Comunicação e Artes',
      item1Sub: 'EBAC & Especializações',
      item1Desc: 'Estudos aprofundados em fotografia e narrativas visuais com mestres do cinema.',
      item2Title: 'Serviço Social',
      item2Sub: 'Bacharelado FMU',
      item2Desc: 'Olhar humanizado e sensibilidade social aplicados à captura de momentos reais.'
    },
    socials: {
      tag: 'CONECTE-SE',
      title: 'ESCOLHA O PERFIL',
      desc: 'Selecione uma das nossas frentes de atuação para acompanhar no Instagram.',
      ig: 'INSTAGRAM',
      wa: 'WHATSAPP',
      be: 'BEHANCE',
      li: 'LINKEDIN',
      fotografia: 'picMI Fotografia',
      producoes: 'picMI Produções'
    },
    experience: {
      tag: 'CARREIRA',
      title: 'Experiência Corporativa',
      visionTitle: 'Vision Produtora',
      visionHandle: '@vision_produtora',
      visionDesc: 'Onde aprendi a realizar Ensaios Corporativos, Ensaios de Gestante, Família, Casamento, Natal, Aniversários, entre outros.',
      photoparkTitle: 'Photopark',
      photoparkHandle: '@photoparkbr',
      photoparkDesc: 'Realizo diariamente trabalhos em eventos e locais como Mundo Pixar, CCXP e Parque da Mônica, com experiência com públicos de todas as idades.'
    },
    portfolio: {
      title: 'PORTFÓLIO',
      desc: 'Capturas que transcendem o momento.',
      categories: {
        destaque: 'DESTAQUES',
        shows: 'SHOWS',
        capa: 'CAPAS',
        clipes: 'CLIPES',
        batalhas: 'BATALHA DE RIMA',
        makingof: 'MAKING OF',
        moda: 'MODA',
        ecommerce: 'E-COMMERCE',
        aniversario: 'ANIVERSÁRIO',
        esportes: 'ESPORTES',
        eventos: 'EVENTOS',
        still: 'STILL'
      }
    },
    services: {
      title: 'SERVIÇOS',
      desc: 'Soluções audiovisuais focadas em identidade e narrativa.'
    },
    contact: {
      tag: 'CONTATO',
      t1: 'VAMOS',
      t2: 'PRODUZIR',
      t3: 'SEU EVENTO?',
      desc: 'Inicie uma conversa para transformar sua ideia em impacto visual.',
      wa: 'WHATSAPP',
      ig: 'INSTAGRAM'
    },
    footer: {
      rights: 'Todos os direitos reservados.'
    }
  },
  en: {
    nav: { home: 'HOME', about: 'ABOUT', academic: 'ACADEMIC', experience: 'EXPERIENCE', socials: 'SOCIALS', portfolio: 'PORTFÓLIO', services: 'SERVICES', contact: 'CONTACT' },
    hero: {
      tagline: 'picMi Photography Experience',
      title1: 'Image is',
      titleAccent: 'communication',
      desc: 'Transmits and translates feelings. Let\'s translate your project or event to the world together!',
      btnPortfolio: 'EXPLORE PORTFOLIO',
      btnAbout: 'ABOUT ME',
      btnAcademic: 'ACADEMIC BACKGROUND',
      btnExperience: 'CORPORATE EXPERIENCE',
      btnSocials: 'SOCIAL MEDIA',
      btnContact: 'GET IN TOUCH'
    },
    about: {
      tag: 'ABOUT ME',
      title: 'Millena Almeida',
      p1: 'Millena Almeida Santos, 26 years old, born on 09/18/1999, in the city of São Paulo...',
      p2: 'I have a facility for speaking and writing...',
      p3: 'I work with respect, creativity, boldness...',
      projects: 'Projects',
      creativity: 'Creativity'
    },
    academic: {
      tag: 'LEVEL UP',
      title: 'Academic Background',
      close: 'X',
      statusTitle: 'SYSTEM_STATUS: ACADEMIC_DATA',
      fullContent: 'Graduated in Photography from EBAC...',
      item1Title: 'Communication and Arts',
      item1Sub: 'EBAC & Specializations',
      item1Desc: 'In-depth studies in photography and visual narratives...',
      item2Title: 'Social Work',
      item2Sub: 'Bachelor FMU',
      item2Desc: 'Humanized look and social sensitivity...'
    },
    socials: {
      tag: 'CONNECT',
      title: 'CHOOSE PROFILE',
      desc: 'Select one of our fronts to follow on Instagram.',
      ig: 'INSTAGRAM',
      wa: 'WHATSAPP',
      be: 'BEHANCE',
      li: 'LINKEDIN',
      fotografia: 'picMI Photography',
      producoes: 'picMI Productions'
    },
    experience: {
      tag: 'CAREER',
      title: 'Corporate Experience',
      visionTitle: 'Vision Producer',
      visionHandle: '@vision_produtora',
      visionDesc: 'Where I learned to perform Corporate Shoots, Pregnancy Shoots, Family, Wedding...',
      photoparkTitle: 'Photopark',
      photoparkHandle: '@photoparkbr',
      photoparkDesc: 'I perform daily work in events and locations such as Mundo Pixar, CCXP...'
    },
    portfolio: {
      title: 'PORTFOLIO',
      desc: 'Capturas que transcendem o momento.',
      categories: {
        destaque: 'HIGHLIGHTS',
        shows: 'SHOWS',
        capa: 'COVERS',
        clipes: 'CLIPS',
        batalhas: 'RHYME BATTLE',
        makingof: 'MAKING OF',
        moda: 'FASHION',
        ecommerce: 'E-COMMERCE',
        aniversario: 'BIRTHDAY',
        esportes: 'SPORTS',
        eventos: 'EVENTS',
        still: 'STILL'
      }
    },
    services: {
      title: 'SERVICES',
      desc: 'Complete audiovisual solutions for your project.'
    },
    contact: {
      tag: 'CONTACT',
      t1: 'LET\'S',
      t2: 'PRODUCE',
      t3: 'YOUR EVENT?',
      desc: 'Contact us for quotes and partnerships.',
      wa: 'WHATSAPP',
      ig: 'INSTAGRAM'
    },
    footer: {
      rights: 'All rights reserved.'
    }
  }
};

export const GET_SERVICES = (lang: 'pt' | 'en'): Service[] => [
  {
    id: '1',
    title: lang === 'pt' ? 'Eventos & Shows' : 'Events & Shows',
    description: lang === 'pt' ? 'Cobertura completa de eventos, festivais e apresentações ao vivo com foco em energia e emoção.' : 'Complete coverage of events, festivals and live performances focusing on energy and emotion.',
    icon: '📸'
  },
  {
    id: '2',
    title: lang === 'pt' ? 'Ensaios Corporativos' : 'Corporate Shoots',
    description: lang === 'pt' ? 'Posicionamento de imagem profissional para empresas e profissionais autônomos.' : 'Professional image positioning for companies and self-employed professionals.',
    icon: '💼'
  },
  {
    id: '3',
    title: lang === 'pt' ? 'Produção Audiovisual' : 'Audiovisual Production',
    description: lang === 'pt' ? 'Direção de fotografia e captação para clipes, making of e conteúdo para redes sociais.' : 'Director of photography and capture for music videos, making of and social media content.',
    icon: '🎥'
  }
];

export const PHOTOS: Photo[] = [
  // Destaques
  { id: 'd1', url: 'https://i.ibb.co/CpWyhttP/MG-3539.jpg', category: 'destaque', title: 'Highlight I' },
  { id: 'd2', url: 'https://i.ibb.co/YF82FPX5/IMG-0712-1.jpg', category: 'destaque', title: 'Highlight II' },
  { id: 'd3', url: 'https://i.ibb.co/Xfpws3Rx/MG-5288.jpg', category: 'destaque', title: 'Highlight III' },
  { id: 'd4', url: 'https://i.ibb.co/j9mN5wJs/MG-3020.jpg', category: 'destaque', title: 'Highlight IV' },
  { id: 'd5', url: 'https://i.ibb.co/PZjcPfVT/MG-2975.jpg', category: 'destaque', title: 'Highlight V' },
  { id: 'd6', url: 'https://i.ibb.co/W41zbqbh/MG-3003.jpg', category: 'destaque', title: 'Highlight VI' },
  
  // Batalhas de Rima
  { id: 'br-1', url: 'https://i.ibb.co/sJj36xHY/MG-5762.jpg', category: 'batalhas', title: 'Batalha Rima MG 5762' },
  { id: 'br-2', url: 'https://i.ibb.co/pjXKNjkY/MG-7870.jpg', category: 'batalhas', title: 'Batalha Rima MG 7870' },
  { id: 'br-3', url: 'https://i.ibb.co/VWHQ2L9P/MG-8407.jpg', category: 'batalhas', title: 'Batalha Rima MG 8407' },
  { id: 'br-4', url: 'https://i.ibb.co/bgvBv9fK/MG-8452.jpg', category: 'batalhas', title: 'Batalha Rima MG 8452' },
  { id: 'br-5', url: 'https://i.ibb.co/1tzFCpFD/MG-8463.jpg', category: 'batalhas', title: 'Batalha Rima MG 8463' },
  { id: 'br-6', url: 'https://i.ibb.co/WTFxjxQ/MG-8540.jpg', category: 'batalhas', title: 'Batalha Rima MG 8540' },
  { id: 'br-7', url: 'https://i.ibb.co/YFxkJ2tz/MG-8590.jpg', category: 'batalhas', title: 'Batalha Rima MG 8590' },
  { id: 'br-8', url: 'https://i.ibb.co/ccPSmV1N/MG-8633.jpg', category: 'batalhas', title: 'Batalha Rima MG 8633' },
  { id: 'br-9', url: 'https://i.ibb.co/0jHCF63L/MG-8957.jpg', category: 'batalhas', title: 'Batalha Rima MG 8957' },
  { id: 'br-10', url: 'https://i.ibb.co/Ng8ygcSM/MG-8959.jpg', category: 'batalhas', title: 'Batalha Rima MG 8959' },
  { id: 'br-11', url: 'https://i.ibb.co/SDWvCHHb/IMG-0993.jpg', category: 'batalhas', title: 'Batalha Rima IMG 0993' },
  { id: 'br-12', url: 'https://i.ibb.co/PsRVrX5r/IMG-2468.jpg', category: 'batalhas', title: 'Batalha Rima IMG 2468' },
  { id: 'br-13', url: 'https://i.ibb.co/9Rv4LJx/IMG-2469.jpg', category: 'batalhas', title: 'Batalha Rima IMG 2469' },
  { id: 'br-14', url: 'https://i.ibb.co/cSfz7t2Z/IMG-2470.jpg', category: 'batalhas', title: 'Batalha Rima IMG 2470' },
  { id: 'br-15', url: 'https://i.ibb.co/j9x4YvkC/IMG-2512.jpg', category: 'batalhas', title: 'Batalha Rima IMG 2512' },
  { id: 'br-16', url: 'https://i.ibb.co/mVxF6Bd5/IMG-2670.jpg', category: 'batalhas', title: 'Batalha Rima IMG 2670' },
  { id: 'br-17', url: 'https://i.ibb.co/CpGFPKyH/IMG-2720.jpg', category: 'batalhas', title: 'Batalha Rima IMG 2720' },
  { id: 'br-18', url: 'https://i.ibb.co/sdhcnszT/IMG-2847.jpg', category: 'batalhas', title: 'Batalha Rima IMG 2847' },
  { id: 'br-19', url: 'https://i.ibb.co/nNMNtp31/IMG-2908.jpg', category: 'batalhas', title: 'Batalha Rima IMG 2908' },
  { id: 'br-20', url: 'https://i.ibb.co/qMwbHC5f/IMG-2963.jpg', category: 'batalhas', title: 'Batalha Rima IMG 2963' },
  { id: 'br-21', url: 'https://i.ibb.co/84SzS09Z/IMG-3055.jpg', category: 'batalhas', title: 'Batalha Rima IMG 3055' },
  { id: 'br-22', url: 'https://i.ibb.co/4g4kNwhm/IMG-3088.jpg', category: 'batalhas', title: 'Batalha Rima IMG 3088' },
  { id: 'br-23', url: 'https://i.ibb.co/1fqt8LpR/IMG-3342.jpg', category: 'batalhas', title: 'Batalha Rima IMG 3342' },
  { id: 'br-24', url: 'https://i.ibb.co/pjp5cPTg/Whats-App-Image-2026-01-21-at-19-51-31.jpg', category: 'batalhas', title: 'Batalha Rima WA 31' },
  { id: 'br-25', url: 'https://i.ibb.co/PGptkXk6/Whats-App-Image-2026-01-21-at-19-51-30-4.jpg', category: 'batalhas', title: 'Batalha Rima WA 30-4' },
  { id: 'br-26', url: 'https://i.ibb.co/0psQRrPd/Whats-App-Image-2026-01-21-at-19-51-30-3.jpg', category: 'batalhas', title: 'Batalha Rima WA 30-3' },
  { id: 'br-27', url: 'https://i.ibb.co/s9d5Y0Ng/Whats-App-Image-2026-01-21-at-19-51-30-2.jpg', category: 'batalhas', title: 'Batalha Rima WA 30-2' },
  { id: 'br-28', url: 'https://i.ibb.co/XkDnczjC/Whats-App-Image-2026-01-21-at-19-51-30-1.jpg', category: 'batalhas', title: 'Batalha Rima WA 30-1' },
  { id: 'br-29', url: 'https://i.ibb.co/QF2S5ydq/Whats-App-Image-2026-01-21-at-19-51-30.jpg', category: 'batalhas', title: 'Batalha Rima WA 30' },
  { id: 'br-30', url: 'https://i.ibb.co/HDB4Khq4/Whats-App-Image-2026-01-21-at-19-51-29.jpg', category: 'batalhas', title: 'Batalha Rima WA 29' },
  { id: 'br-31', url: 'https://i.ibb.co/9HQTPRN2/MG-2511.jpg', category: 'batalhas', title: 'Batalha Rima MG 2511' },
  { id: 'br-32', url: 'https://i.ibb.co/0pTdDgRP/MG-2521.jpg', category: 'batalhas', title: 'Batalha Rima MG 2521' },
  { id: 'br-33', url: 'https://i.ibb.co/0jv4NbvM/MG-2546.jpg', category: 'batalhas', title: 'Batalha Rima MG 2546' },
  { id: 'br-34', url: 'https://i.ibb.co/XZWYQKK1/MG-2642.jpg', category: 'batalhas', title: 'Batalha Rima MG 2642' },
  { id: 'br-35', url: 'https://i.ibb.co/rRVPttsd/MG-2648.jpg', category: 'batalhas', title: 'Batalha Rima MG 2648' },
  { id: 'br-36', url: 'https://i.ibb.co/GfZMJM7w/MG-2781.jpg', category: 'batalhas', title: 'Batalha Rima MG 2781' },
  { id: 'br-37', url: 'https://i.ibb.co/RTb823ZJ/MG-2883.jpg', category: 'batalhas', title: 'Batalha Rima MG 2883' },
  { id: 'br-38', url: 'https://i.ibb.co/6cMwwNbD/MG-3199.jpg', category: 'batalhas', title: 'Batalha Rima MG 3199' },
  { id: 'br-39', url: 'https://i.ibb.co/RG1rBsYs/MG-3202.jpg', category: 'batalhas', title: 'Batalha Rima MG 3202' },
  { id: 'br-40', url: 'https://i.ibb.co/B5R13N98/MG-3232.jpg', category: 'batalhas', title: 'Batalha Rima MG 3232' },
  { id: 'br-41', url: 'https://i.ibb.co/DPmGkhvP/MG-3390.jpg', category: 'batalhas', title: 'Batalha Rima MG 3390' },
  { id: 'br-42', url: 'https://i.ibb.co/PvswdkmP/MG-3508.jpg', category: 'batalhas', title: 'Batalha Rima MG 3508' },
  { id: 'br-43', url: 'https://i.ibb.co/jPJsCy04/MG-3523.jpg', category: 'batalhas', title: 'Batalha Rima MG 3523' },
  { id: 'br-44', url: 'https://i.ibb.co/TDG9KLCy/MG-3525.jpg', category: 'batalhas', title: 'Batalha Rima MG 3525' },
  { id: 'br-45', url: 'https://i.ibb.co/Pzsc1Fdr/MG-3527.jpg', category: 'batalhas', title: 'Batalha Rima MG 3527' },
  { id: 'br-46', url: 'https://i.ibb.co/1JskMcVW/MG-3539.jpg', category: 'batalhas', title: 'Batalha Rima MG 3539' },
  { id: 'br-47', url: 'https://i.ibb.co/HT4MgnfK/MG-3560.jpg', category: 'batalhas', title: 'Batalha Rima MG 3560' },
  { id: 'br-48', url: 'https://i.ibb.co/wFD8HfGY/MG-3569.jpg', category: 'batalhas', title: 'Batalha Rima MG 3569' },
  { id: 'br-49', url: 'https://i.ibb.co/p85QgzL/MG-3629.jpg', category: 'batalhas', title: 'Batalha Rima MG 3629' },
  { id: 'br-50', url: 'https://i.ibb.co/dsC3GG6w/MG-3645.jpg', category: 'batalhas', title: 'Batalha Rima MG 3645' },
  { id: 'br-51', url: 'https://i.ibb.co/zHP9WQBL/MG-3664.jpg', category: 'batalhas', title: 'Batalha Rima MG 3664' },
  { id: 'br-52', url: 'https://i.ibb.co/JRcFsm6z/MG-3669.jpg', category: 'batalhas', title: 'Batalha Rima MG 3669' },
  { id: 'br-53', url: 'https://i.ibb.co/2HsMFvd/MG-3688.jpg', category: 'batalhas', title: 'Batalha Rima MG 3688' },
  { id: 'br-54', url: 'https://i.ibb.co/FbM5Mysv/MG-3690.jpg', category: 'batalhas', title: 'Batalha Rima MG 3690' },
  
  // Eventos
  { id: 'ev-1', url: 'https://i.ibb.co/ksZ7371j/MG-1504.jpg', category: 'eventos', title: 'Evento MG 1504' },
  { id: 'ev-2', url: 'https://i.ibb.co/kVnd2qTf/MG-1400.jpg', category: 'eventos', title: 'Evento MG 1400' },
  { id: 'ev-3', url: 'https://i.ibb.co/v4Tf5CP6/MG-1349.jpg', category: 'eventos', title: 'Evento MG 1349' },
  { id: 'ev-4', url: 'https://i.ibb.co/zWY7vL5d/MG-1336.jpg', category: 'eventos', title: 'Evento MG 1336' },
  { id: 'ev-5', url: 'https://i.ibb.co/60WS504f/MG-1318.jpg', category: 'eventos', title: 'Evento MG 1318' },
  { id: 'ev-6', url: 'https://i.ibb.co/6RqbP1dW/MG-1304.jpg', category: 'eventos', title: 'Evento MG 1304' },
  { id: 'ev-7', url: 'https://i.ibb.co/Kp1XcRZN/MG-1260.jpg', category: 'eventos', title: 'Evento MG 1260' },
  { id: 'ev-8', url: 'https://i.ibb.co/gMmdQ1ny/MG-1254.jpg', category: 'eventos', title: 'Evento MG 1254' },
  { id: 'ev-9', url: 'https://i.ibb.co/hxhF6kZg/MG-1217.jpg', category: 'eventos', title: 'Evento MG 1217' },
  { id: 'ev-10', url: 'https://i.ibb.co/5XYzJGvH/MG-1172.jpg', category: 'eventos', title: 'Evento MG 1172' },
  { id: 'ev-11', url: 'https://i.ibb.co/tMkjwY88/MG-1143.jpg', category: 'eventos', title: 'Evento MG 1143' },
  { id: 'ev-12', url: 'https://i.ibb.co/8n9WsmSG/MG-1105.jpg', category: 'eventos', title: 'Evento MG 1105' },
  { id: 'ev-13', url: 'https://i.ibb.co/fc8fjyB/MG-1099.jpg', category: 'eventos', title: 'Evento MG 1099' },
  { id: 'ev-14', url: 'https://i.ibb.co/V0sTMgw2/MG-1083.jpg', category: 'eventos', title: 'Evento MG 1083' },
  { id: 'ev-15', url: 'https://i.ibb.co/t5vBh5L/MG-1052.jpg', category: 'eventos', title: 'Evento MG 1052' },
  { id: 'ev-16', url: 'https://i.ibb.co/Mxk52tDr/MG-0981.jpg', category: 'eventos', title: 'Evento MG 0981' },
  { id: 'ev-17', url: 'https://i.ibb.co/wrZ8Z7gj/MG-0912.jpg', category: 'eventos', title: 'Evento MG 0912' },
  { id: 'ev-18', url: 'https://i.ibb.co/YFG8GnxK/MG-0883.jpg', category: 'eventos', title: 'Evento MG 0883' },
  { id: 'ev-19', url: 'https://i.ibb.co/0y8yZ9Bn/MG-0719.jpg', category: 'eventos', title: 'Evento MG 0719' },

  // Moda
  { id: 'md-1', url: 'https://i.ibb.co/fzNP50KD/IMG-3485.jpg', category: 'moda', title: 'Fashion Session 3485' },
  { id: 'md-2', url: 'https://i.ibb.co/gMqybL4Z/IMG-3483.jpg', category: 'moda', title: 'Fashion Session 3483' },
  { id: 'md-3', url: 'https://i.ibb.co/CsYcyFdz/IMG-3481.jpg', category: 'moda', title: 'Fashion Session 3481' },
  { id: 'md-4', url: 'https://i.ibb.co/vCR646XV/IMG-3479.jpg', category: 'moda', title: 'Fashion Session 3479' },
  { id: 'md-5', url: 'https://i.ibb.co/S49Kr3hZ/IMG-3478.jpg', category: 'moda', title: 'Fashion Session 3478' },
  { id: 'md-6', url: 'https://i.ibb.co/jPpFYSP2/IMG-3476.jpg', category: 'moda', title: 'Fashion Session 3476' },
  { id: 'md-7', url: 'https://i.ibb.co/4Z8rrjbz/IMG-3477.jpg', category: 'moda', title: 'Fashion Session 3477' },

  // Capas
  { id: 'cp-1', url: 'https://i.ibb.co/4gm87mnr/IMG-0712-1.jpg', category: 'capa', title: 'Capa IMG 0712' },
  { id: 'cp-4', url: 'https://i.ibb.co/ZRfjTRhD/MG-5852.jpg', category: 'capa', title: 'Capa MG 5852' },
  { id: 'cp-3', url: 'https://i.ibb.co/3ykXCzGQ/MG-9233.jpg', category: 'capa', title: 'Capa MG 9233' },
  { id: 'cp-2', url: 'https://i.ibb.co/jkR99PqY/MG-7621.jpg', category: 'capa', title: 'Capa MG 7621' },
  { id: 'cp-5', url: 'https://i.ibb.co/Qj1G3Gdm/MG-6692.jpg', category: 'capa', title: 'Capa MG 6692' },
  { id: 'cp-6', url: 'https://i.ibb.co/MDfjF9K3/MG-5873.jpg', category: 'capa', title: 'Capa MG 5873' },
  { id: 'cp-7', url: 'https://i.ibb.co/d0p8Y3mW/MG-5865.jpg', category: 'capa', title: 'Capa MG 5865' },

  // Esportes
  { id: 'sp-1', url: 'https://i.ibb.co/h1X9fL5Q/MG-5768.jpg', category: 'esportes', title: 'Esporte MG 5768' },
  { id: 'sp-2', url: 'https://i.ibb.co/5gyrc3fX/MG-5766.jpg', category: 'esportes', title: 'Esporte MG 5766' },
  { id: 'sp-3', url: 'https://i.ibb.co/rf33kG2H/MG-5722.jpg', category: 'esportes', title: 'Esporte MG 5722' },
  { id: 'sp-4', url: 'https://i.ibb.co/LhH97hny/MG-5719.jpg', category: 'esportes', title: 'Esporte MG 5719' },
  { id: 'sp-5', url: 'https://i.ibb.co/5XQ69zXC/MG-5700.jpg', category: 'esportes', title: 'Esporte MG 5700' },
  { id: 'sp-6', url: 'https://i.ibb.co/847CFn1M/MG-5718.jpg', category: 'esportes', title: 'Esporte MG 5718' },
  { id: 'sp-25', url: 'https://i.ibb.co/FkQksMQn/IMG-2759.jpg', category: 'esportes', title: 'IMG 2759' },
  { id: 'sp-26', url: 'https://i.ibb.co/Gzh4VwQ/IMG-2757.jpg', category: 'esportes', title: 'IMG 2757' },
  { id: 'sp-7', url: 'https://i.ibb.co/FL3Z2Lrh/MG-4513.jpg', category: 'esportes', title: 'Esporte MG 4513' },
  { id: 'sp-8', url: 'https://i.ibb.co/zH6zgzPg/MG-4503.jpg', category: 'esportes', title: 'Esporte MG 4503' },
  { id: 'sp-9', url: 'https://i.ibb.co/MyvZYvPm/MG-4500.jpg', category: 'esportes', title: 'Esporte MG 4500' },
  { id: 'sp-10', url: 'https://i.ibb.co/gbx8wb0K/MG-4496.jpg', category: 'esportes', title: 'Esporte MG 4496' },
  { id: 'sp-11', url: 'https://i.ibb.co/spJ8SCpf/MG-4489.jpg', category: 'esportes', title: 'Esporte MG 4489' },
  { id: 'sp-12', url: 'https://i.ibb.co/70kZKcx/MG-4463.jpg', category: 'esportes', title: 'Esporte MG 4463' },
  { id: 'sp-13', url: 'https://i.ibb.co/844FfNtm/MG-4461.jpg', category: 'esportes', title: 'Esporte MG 4461' },
  { id: 'sp-14', url: 'https://i.ibb.co/93TmprvB/MG-4446.jpg', category: 'esportes', title: 'Esporte MG 4446' },
  { id: 'sp-15', url: 'https://i.ibb.co/9kgBH37k/MG-4443.jpg', category: 'esportes', title: 'Esporte MG 4443' },
  { id: 'sp-16', url: 'https://i.ibb.co/XZ7CTdsc/MG-4432.jpg', category: 'esportes', title: 'Esporte MG 4432' },
  { id: 'sp-17', url: 'https://i.ibb.co/HDc63BHK/MG-4410.jpg', category: 'esportes', title: 'Esporte MG 4410' },
  { id: 'sp-18', url: 'https://i.ibb.co/39NjYs7J/MG-4409.jpg', category: 'esportes', title: 'Esporte MG 4409' },
  { id: 'sp-19', url: 'https://i.ibb.co/bg9WHh6d/MG-4405.jpg', category: 'esportes', title: 'Esporte MG 4405' },
  { id: 'sp-20', url: 'https://i.ibb.co/dsnSdF5y/MG-4381.jpg', category: 'esportes', title: 'Esporte MG 4381' },
  { id: 'sp-21', url: 'https://i.ibb.co/dZnsy1v/MG-4368.jpg', category: 'esportes', title: 'Esporte MG 4368' },
  { id: 'sp-22', url: 'https://i.ibb.co/DHSpVYkg/MG-4364.jpg', category: 'esportes', title: 'Esporte MG 4364' },
  { id: 'sp-23', url: 'https://i.ibb.co/q3CLpvm7/MG-4317.jpg', category: 'esportes', title: 'Esporte MG 4317' },
  { id: 'sp-24', url: 'https://i.ibb.co/67q3T3Cv/MG-4340.jpg', category: 'esportes', title: 'Esporte MG 4340' },

  // Aniversario
  { id: 'an-1', url: 'https://i.ibb.co/LzL1kGWn/MG-4751.jpg', category: 'aniversario', title: 'Aniversário MG 4751' },
  { id: 'an-2', url: 'https://i.ibb.co/ksTWMGhF/MG-4749.jpg', category: 'aniversario', title: 'Aniversário MG 4749' },
  { id: 'an-3', url: 'https://i.ibb.co/9m96mrNY/MG-4713.jpg', category: 'aniversario', title: 'Aniversário MG 4713' },
  { id: 'an-4', url: 'https://i.ibb.co/QGGQr0F/MG-4711.jpg', category: 'aniversario', title: 'Aniversário MG 4711' },
  { id: 'an-5', url: 'https://i.ibb.co/p7nWBpn/MG-4689.jpg', category: 'aniversario', title: 'Aniversário MG 4689' },
  { id: 'an-6', url: 'https://i.ibb.co/Nn1YyS1L/MG-4688.jpg', category: 'aniversario', title: 'Aniversário MG 4688' },
  { id: 'an-7', url: 'https://i.ibb.co/ccSXtVWB/MG-4650.jpg', category: 'aniversario', title: 'Aniversário MG 4650' },
  { id: 'an-8', url: 'https://i.ibb.co/RJTHBtL/MG-4639.jpg', category: 'aniversario', title: 'Aniversário MG 4639' },
  { id: 'an-9', url: 'https://i.ibb.co/0pGTgJzC/MG-4627.jpg', category: 'aniversario', title: 'Aniversário MG 4627' },
  { id: 'an-10', url: 'https://i.ibb.co/ynLyhS2N/MG-4621.jpg', category: 'aniversario', title: 'Aniversário MG 4621' },
  { id: 'an-11', url: 'https://i.ibb.co/RTrmB2Z6/MG-4617.jpg', category: 'aniversario', title: 'Aniversário MG 4617' },
  { id: 'an-12', url: 'https://i.ibb.co/6c96WNXM/MG-4615.jpg', category: 'aniversario', title: 'Aniversário MG 4615' },
  { id: 'an-13', url: 'https://i.ibb.co/MyNM4GKS/MG-4886.jpg', category: 'aniversario', title: 'Aniversário MG 4886' },
  { id: 'an-14', url: 'https://i.ibb.co/5hMjJkT4/MG-4829.jpg', category: 'aniversario', title: 'Aniversário MG 4829' },
  { id: 'an-15', url: 'https://i.ibb.co/GG5M7Gv/MG-4826.jpg', category: 'aniversario', title: 'Aniversário MG 4826' },
  { id: 'an-16', url: 'https://i.ibb.co/Ngbm7CK7/MG-4822.jpg', category: 'aniversario', title: 'Aniversário MG 4822' },
  { id: 'an-17', url: 'https://i.ibb.co/rGzc2wJN/MG-4820.jpg', category: 'aniversario', title: 'Aniversário MG 4820' },
  { id: 'an-18', url: 'https://i.ibb.co/24CTcTn/MG-4814.jpg', category: 'aniversario', title: 'Aniversário MG 4814' },
  { id: 'an-19', url: 'https://i.ibb.co/PzZy4fDR/MG-4792.jpg', category: 'aniversario', title: 'Aniversário MG 4792' },
  { id: 'an-20', url: 'https://i.ibb.co/jP8gwmCm/MG-4774.jpg', category: 'aniversario', title: 'Aniversário MG 4774' },
  { id: 'an-21', url: 'https://i.ibb.co/kVkKDCFy/MG-4966.jpg', category: 'aniversario', title: 'Aniversário MG 4966' },
  { id: 'an-22', url: 'https://i.ibb.co/Vcm6v4jH/MG-4960.jpg', category: 'aniversario', title: 'Aniversário MG 4960' },
  { id: 'an-23', url: 'https://i.ibb.co/mFRh4TgW/MG-4959.jpg', category: 'aniversario', title: 'Aniversário MG 4959' },
  { id: 'an-24', url: 'https://i.ibb.co/GQ5DYz7x/MG-4947.jpg', category: 'aniversario', title: 'Aniversário MG 4947' },
  { id: 'an-25', url: 'https://i.ibb.co/Fkk4X2ZW/MG-4936.jpg', category: 'aniversario', title: 'Aniversário MG 4936' },
  { id: 'an-26', url: 'https://i.ibb.co/zVG4JsjS/MG-4939.jpg', category: 'aniversario', title: 'Aniversário MG 4939' },
  { id: 'an-27', url: 'https://i.ibb.co/4RFThcXQ/MG-4935.jpg', category: 'aniversario', title: 'Aniversário MG 4935' },
  { id: 'an-28', url: 'https://i.ibb.co/SDZ2ZcWf/MG-4928.jpg', category: 'aniversario', title: 'Aniversário MG 4928' },
  { id: 'an-29', url: 'https://i.ibb.co/hRHsxtbs/MG-4926.jpg', category: 'aniversario', title: 'Aniversário MG 4926' },
  { id: 'an-30', url: 'https://i.ibb.co/FbYGkgc4/MG-4915.jpg', category: 'aniversario', title: 'Aniversário MG 4915' },
  { id: 'an-31', url: 'https://i.ibb.co/zV1R0jbG/MG-4914.jpg', category: 'aniversario', title: 'Aniversário MG 4914' },
  { id: 'an-32', url: 'https://i.ibb.co/qL2WwFY0/MG-4897.jpg', category: 'aniversario', title: 'Aniversário MG 4897' },
  { id: 'an-33', url: 'https://i.ibb.co/dwtqbmSY/MG-4906.jpg', category: 'aniversario', title: 'Aniversário MG 4906' },

  // Shows (Top Order Requested)
  { id: 's-54', url: 'https://i.ibb.co/93tcQPhr/MG-3100.jpg', category: 'shows', title: 'Show MG 3100' },
  { id: 's-53', url: 'https://i.ibb.co/hFFJx6bV/MG-3095.jpg', category: 'shows', title: 'Show MG 3095' },
  { id: 's-52', url: 'https://i.ibb.co/Rp83B1rp/MG-3113.jpg', category: 'shows', title: 'Show MG 3113' },
  { id: 's-51', url: 'https://i.ibb.co/G48qhPqx/MG-3115.jpg', category: 'shows', title: 'Show MG 3115' },
  { id: 's-50', url: 'https://i.ibb.co/JFmKvx0m/MG-3128.jpg', category: 'shows', title: 'Show MG 3128' },
  { id: 's-49', url: 'https://i.ibb.co/kVMb9hPt/MG-3176.jpg', category: 'shows', title: 'Show MG 3176' },
  { id: 's-28', url: 'https://i.ibb.co/9HRP8fPq/IMG-5279-1.jpg', category: 'shows', title: 'Show IMG 5279' },
  { id: 's-26', url: 'https://i.ibb.co/fYtPqQgK/IMG-5280.jpg', category: 'shows', title: 'Show IMG 5280' },
  { id: 's-25', url: 'https://i.ibb.co/HTF2D7TC/IMG-5281-1.jpg', category: 'shows', title: 'Show IMG 5281' },
  { id: 's-24', url: 'https://i.ibb.co/Q7r9wL98/IMG-5282-1.jpg', category: 'shows', title: 'Show IMG 5282' },
  { id: 's-23', url: 'https://i.ibb.co/6cDdL7KW/IMG-5283.jpg', category: 'shows', title: 'Show IMG 5283' },
  { id: 's-22', url: 'https://i.ibb.co/GQMVC7gg/IMG-5288.jpg', category: 'shows', title: 'Show IMG 5288' },
  { id: 's-21', url: 'https://i.ibb.co/dwbgzxvk/IMG-5298-1.jpg', category: 'shows', title: 'Show IMG 5298' },
  { id: 's-20', url: 'https://i.ibb.co/zTYX5fhs/IMG-5299.jpg', category: 'shows', title: 'Show IMG 5299' },
  { id: 's-19', url: 'https://i.ibb.co/HTJS0M6C/IMG-5304.jpg', category: 'shows', title: 'Show IMG 5304' },
  
  // Shows (Remaining)
  { id: 's1', url: 'https://i.ibb.co/hFLv9wqX/IMG-0060.jpg', category: 'shows', title: 'Live Performance' },
  { id: 's-2', url: 'https://i.ibb.co/SXHtDMg6/MG-9226.jpg', category: 'shows', title: 'Show MG 9226' },
  { id: 's-3', url: 'https://i.ibb.co/RT3K0XY6/MG-9203.jpg', category: 'shows', title: 'Show MG 9203' },
  { id: 's-4', url: 'https://i.ibb.co/0VhmfsYZ/MG-9201.jpg', category: 'shows', title: 'Show MG 9201' },
  { id: 's-5', url: 'https://i.ibb.co/23rts1RV/MG-9189.jpg', category: 'shows', title: 'Show MG 9189' },
  { id: 's-6', url: 'https://i.ibb.co/PGcbVGCs/MG-9179.jpg', category: 'shows', title: 'Show MG 9179' },
  { id: 's-7', url: 'https://i.ibb.co/fz2DfC84/IMG-1244-1.jpg', category: 'shows', title: 'Show IMG 1244' },
  { id: 's-8', url: 'https://i.ibb.co/70wrHXt/MG-9178.jpg', category: 'shows', title: 'Show MG 9178' },
  { id: 's-9', url: 'https://i.ibb.co/Y44KNQxs/IMG-1241.jpg', category: 'shows', title: 'Show IMG 1241' },
  { id: 's-10', url: 'https://i.ibb.co/ZR1HyyDG/IMG-1234-1.jpg', category: 'shows', title: 'Show IMG 1234' },
  { id: 's-11', url: 'https://i.ibb.co/Myftdx9L/IMG-1218-1.jpg', category: 'shows', title: 'Show IMG 1218' },
  { id: 's-12', url: 'https://i.ibb.co/Dgk4VT2h/IMG-1219-1.jpg', category: 'shows', title: 'Show IMG 1219' },
  { id: 's-13', url: 'https://i.ibb.co/prbS12db/IMG-1129.jpg', category: 'shows', title: 'Show IMG 1129' },
  { id: 's-14', url: 'https://i.ibb.co/xtRqKYRc/IMG-1128.jpg', category: 'shows', title: 'Show IMG 1128' },
  { id: 's-15', url: 'https://i.ibb.co/gZW46HGY/IMG-1040.jpg', category: 'shows', title: 'Show IMG 1040' },
  { id: 's-16', url: 'https://i.ibb.co/ynpHj3Nm/MG-9487.jpg', category: 'shows', title: 'Show MG 9487' },
  { id: 's-17', url: 'https://i.ibb.co/39rx0vLV/MG-9484.jpg', category: 'shows', title: 'Show MG 9484' },
  { id: 's-18', url: 'https://i.ibb.co/bgBNBz9c/MG-9448.jpg', category: 'shows', title: 'Show MG 9448' },
  { id: 's-27', url: 'https://i.ibb.co/wNzV0Py1/IMG-3187.jpg', category: 'shows', title: 'Show IMG 3187' },
  { id: 's-29', url: 'https://i.ibb.co/gFMq6WGM/IMG-3184.jpg', category: 'shows', title: 'Show IMG 3184' },
  { id: 's-30', url: 'https://i.ibb.co/Fq04kRRT/IMG-3183-1.jpg', category: 'shows', title: 'Show IMG 3183' },
  { id: 's-31', url: 'https://i.ibb.co/DHgjdP7d/IMG-3179.jpg', category: 'shows', title: 'Show IMG 3179' },
  { id: 's-32', url: 'https://i.ibb.co/MxjYgfkB/IMG-3177.jpg', category: 'shows', title: 'Show IMG 3177' },
  { id: 's-33', url: 'https://i.ibb.co/HfgMzGhc/IMG-4274.jpg', category: 'shows', title: 'Show IMG 4274' },
  { id: 's-34', url: 'https://i.ibb.co/MDD4G5yW/IMG-4272-1.jpg', category: 'shows', title: 'Show IMG 4272' },
  { id: 's-35', url: 'https://i.ibb.co/CKgcpZyS/IMG-4271.jpg', category: 'shows', title: 'Show IMG 4271' },
  { id: 's-36', url: 'https://i.ibb.co/cht6pDv6/IMG-4266.jpg', category: 'shows', title: 'Show IMG 4266' },
  { id: 's-37', url: 'https://i.ibb.co/Ps7T7Rcj/IMG-4259-1.jpg', category: 'shows', title: 'Show IMG 4259' },
  { id: 's-38', url: 'https://i.ibb.co/N6GpMdm5/IMG-4227-1.jpg', category: 'shows', title: 'Show IMG 4227' },
  { id: 's-39', url: 'https://i.ibb.co/0VQwx8KF/IMG-4224.jpg', category: 'shows', title: 'Show IMG 4224' },
  { id: 's-40', url: 'https://i.ibb.co/nspX4bbk/IMG-4216.jpg', category: 'shows', title: 'Show IMG 4216' },
  { id: 's-41', url: 'https://i.ibb.co/nshxF8qm/IMG-4215-1.jpg', category: 'shows', title: 'Show IMG 4215' },
  { id: 's-42', url: 'https://i.ibb.co/Kxrp5MFQ/IMG-4214.jpg', category: 'shows', title: 'Show IMG 4214' },
  { id: 's-43', url: 'https://i.ibb.co/xt0jCV8W/IMG-0671.jpg', category: 'shows', title: 'Show IMG 0671' },
  { id: 's-44', url: 'https://i.ibb.co/5WvsjJrH/IMG-0662.jpg', category: 'shows', title: 'Show IMG 0662' },
  { id: 's-45', url: 'https://i.ibb.co/8DqSKTbG/IMG-0598-1.jpg', category: 'shows', title: 'Show IMG 0598' },
  { id: 's-46', url: 'https://i.ibb.co/hxSTTrHp/IMG-0577.jpg', category: 'shows', title: 'Show IMG 0577' },
  { id: 's-47', url: 'https://i.ibb.co/s9KJdyPb/IMG-0565-1.jpg', category: 'shows', title: 'Show IMG 0565' },
  { id: 's-48', url: 'https://i.ibb.co/yFtj7Xf4/IMG-0554-1.jpg', category: 'shows', title: 'Show IMG 0554' },

  // Making Of
  { id: 'mo-1', url: 'https://i.ibb.co/xyhhW8s/MG-8312.jpg', category: 'makingof', title: 'Making Of MG 8312' },
  { id: 'mo-2', url: 'https://i.ibb.co/4wFfPVbR/MG-8303.jpg', category: 'makingof', title: 'Making Of MG 8303' },
  { id: 'mo-3', url: 'https://i.ibb.co/9mSczg1s/MG-8301.jpg', category: 'makingof', title: 'Making Of MG 8301' },
  { id: 'mo-4', url: 'https://i.ibb.co/kV5xtFbQ/MG-8296.jpg', category: 'makingof', title: 'Making Of MG 8296' },
  { id: 'mo-5', url: 'https://i.ibb.co/Psqfx0Hw/MG-8294.jpg', category: 'makingof', title: 'Making Of MG 8294' },
  { id: 'mo-6', url: 'https://i.ibb.co/B2SNZ3mZ/MG-8293.jpg', category: 'makingof', title: 'Making Of MG 8293' },
  { id: 'mo-7', url: 'https://i.ibb.co/h1FhWCsQ/MG-8280.jpg', category: 'makingof', title: 'Making Of MG 8280' },
  { id: 'mo-8', url: 'https://i.ibb.co/JwTHfPQG/MG-8277.jpg', category: 'makingof', title: 'Making Of MG 8277' },
  { id: 'mo-9', url: 'https://i.ibb.co/4R8rfDvV/MG-8276.jpg', category: 'makingof', title: 'Making Of MG 8276' },
  { id: 'mo-10', url: 'https://i.ibb.co/Tqm1bS32/MG-8275.jpg', category: 'makingof', title: 'Making Of MG 8275' },
  { id: 'mo-11', url: 'https://i.ibb.co/JRkhhh9p/MG-8274.jpg', category: 'makingof', title: 'Making Of MG 8274' },
  { id: 'mo-12', url: 'https://i.ibb.co/qLNf7XyQ/MG-8263.jpg', category: 'makingof', title: 'Making Of MG 8263' },
  { id: 'mo-13', url: 'https://i.ibb.co/Xr4sfHpc/MG-8258.jpg', category: 'makingof', title: 'Making Of MG 8258' },
  { id: 'mo-14', url: 'https://i.ibb.co/NnbbHv8f/MG-8253.jpg', category: 'makingof', title: 'Making Of MG 8253' },
  { id: 'mo-15', url: 'https://i.ibb.co/wNdQckpX/MG-8249.jpg', category: 'makingof', title: 'Making Of MG 8249' },
  { id: 'mo-16', url: 'https://i.ibb.co/vCHbS0cN/MG-8240.jpg', category: 'makingof', title: 'Making Of MG 8240' },
  { id: 'mo-17', url: 'https://i.ibb.co/SwRyQmpQ/MG-8235.jpg', category: 'makingof', title: 'Making Of MG 8235' },
  { id: 'mo-18', url: 'https://i.ibb.co/CphqZ655/MG-8234.jpg', category: 'makingof', title: 'Making Of MG 8234' },
  { id: 'mo-19', url: 'https://i.ibb.co/NdPJJsz6/MG-8228.jpg', category: 'makingof', title: 'Making Of MG 8228' },
  { id: 'mo-20', url: 'https://i.ibb.co/bRjC9jwJ/MG-8221.jpg', category: 'makingof', title: 'Making Of MG 8221' },
  { id: 'mo-21', url: 'https://i.ibb.co/cK5vd81b/MG-8207.jpg', category: 'makingof', title: 'Making Of MG 8207' },
  { id: 'mo-22', url: 'https://i.ibb.co/GQ8ktXyB/MG-8211.jpg', category: 'makingof', title: 'Making Of MG 8211' },
  { id: 'mo-23', url: 'https://i.ibb.co/RT18fywD/MG-8204.jpg', category: 'makingof', title: 'Making Of MG 8204' },
  { id: 'mo-24', url: 'https://i.ibb.co/fGXYVB2t/MG-8196.jpg', category: 'makingof', title: 'Making Of MG 8196' },
  { id: 'mo-25', url: 'https://i.ibb.co/Qvg0hgPc/MG-8194.jpg', category: 'makingof', title: 'Making Of MG 8194' },
  { id: 'mo-26', url: 'https://i.ibb.co/HTThR2jb/MG-8185.jpg', category: 'makingof', title: 'Making Of MG 8185' },
  { id: 'mo-27', url: 'https://i.ibb.co/Wp3jRmTS/MG-8177.jpg', category: 'makingof', title: 'Tableau 8177' },
  { id: 'mo-28', url: 'https://i.ibb.co/Q7mcj7dh/MG-8175.jpg', category: 'makingof', title: 'Making Of MG 8175' },
  { id: 'mo-29', url: 'https://i.ibb.co/Z5xBvG9/MG-8174.jpg', category: 'makingof', title: 'Making Of MG 8174' },
  { id: 'mo-30', url: 'https://i.ibb.co/Q3jMrR9q/MG-8172.jpg', category: 'makingof', title: 'Making Of MG 8172' },
  { id: 'mo-31', url: 'https://i.ibb.co/ds05Pn4H/MG-8170.jpg', category: 'makingof', title: 'Making Of MG 8170' },
  { id: 'mo-32', url: 'https://i.ibb.co/2Yskk2kD/MG-8124.jpg', category: 'makingof', title: 'Making Of MG 8124' },
  { id: 'mo-33', url: 'https://i.ibb.co/1fQSGmbM/MG-8121.jpg', category: 'makingof', title: 'Making Of MG 8121' },
  { id: 'mo-34', url: 'https://i.ibb.co/4Dy7Qn2/MG-8117.jpg', category: 'makingof', title: 'Making Of MG 8117' },
  { id: 'mo-35', url: 'https://i.ibb.co/SCGphWG/MG-8101.jpg', category: 'makingof', title: 'Making Of MG 8101' },
  { id: 'mo-36', url: 'https://i.ibb.co/Wdv7SvJ/MG-8105.jpg', category: 'makingof', title: 'Making Of MG 8105' },

  // Still
  { id: 'st-39', url: 'https://i.ibb.co/qT9kn2X/MG-5317.jpg', category: 'still', title: 'Still MG 5317' },
  { id: 'st-40', url: 'https://i.ibb.co/XrT9fc35/MG-5312.jpg', category: 'still', title: 'Still MG 5312' },
  { id: 'st-41', url: 'https://i.ibb.co/Z1zDZ88X/MG-5308.jpg', category: 'still', title: 'Still MG 5308' },
  { id: 'st-42', url: 'https://i.ibb.co/qLRhmZQT/MG-5300.jpg', category: 'still', title: 'Still MG 5300' },
  { id: 'st-43', url: 'https://i.ibb.co/DPRgc4cV/MG-5297.jpg', category: 'still', title: 'Still MG 5297' },
  { id: 'st-44', url: 'https://i.ibb.co/KpgyK2Wn/MG-5293.jpg', category: 'still', title: 'Still MG 5293' },
  { id: 'st-45', url: 'https://i.ibb.co/DXTSVs5/MG-5289.jpg', category: 'still', title: 'Still MG 5289' },
  { id: 'st-46', url: 'https://i.ibb.co/CK9gQ2b5/MG-5281.jpg', category: 'still', title: 'Still MG 5281' },
  { id: 'st-47', url: 'https://i.ibb.co/7N8qydX6/MG-5279.jpg', category: 'still', title: 'Still MG 5279' },
  { id: 'st-48', url: 'https://i.ibb.co/VpYd4Xns/MG-5260.jpg', category: 'still', title: 'Still MG 5260' },
  { id: 'st-49', url: 'https://i.ibb.co/4gNfBcF2/MG-5242.jpg', category: 'still', title: 'Still MG 5242' },
  { id: 'st-50', url: 'https://i.ibb.co/nsTktxnY/MG-5233.jpg', category: 'still', title: 'Still MG 5233' },
  { id: 'st-51', url: 'https://i.ibb.co/Q7617zRm/MG-5232.jpg', category: 'still', title: 'Still MG 5232' },
  { id: 'st-52', url: 'https://i.ibb.co/ynghVkbR/MG-5230.jpg', category: 'still', title: 'Still MG 5230' },
  { id: 'st-53', url: 'https://i.ibb.co/Kc8DpfMh/MG-5225.jpg', category: 'still', title: 'Still MG 5225' },
  { id: 'st-55', url: 'https://i.ibb.co/bjBGQKCd/MG-5214.jpg', category: 'still', title: 'Still MG 5214' },
  { id: 'st-56', url: 'https://i.ibb.co/kgDrD5Z0/MG-5212.jpg', category: 'still', title: 'Still MG 5212' },
  
  // Remaining Still
  { id: 'st-1', url: 'https://i.ibb.co/60R82Cyj/IMG-6091.jpg', category: 'still', title: 'Still IMG 6091' },
  { id: 'st-2', url: 'https://i.ibb.co/GQcDn15g/IMG-0768.jpg', category: 'still', title: 'Still IMG 0768' },
  { id: 'st-3', url: 'https://i.ibb.co/27NmY2BZ/IMG-0744-1.jpg', category: 'still', title: 'Still IMG 0744' },
  { id: 'st-4', url: 'https://i.ibb.co/CKQkt7PK/IMG-0750.jpg', category: 'still', title: 'Still IMG 0750' },
  { id: 'st-5', url: 'https://i.ibb.co/0VBzp9X2/IMG-0739-1.jpg', category: 'still', title: 'Still IMG 0739' },
  { id: 'st-6', url: 'https://i.ibb.co/MD2sLdRc/IMG-0722.jpg', category: 'still', title: 'Still IMG 0722' },
  { id: 'st-7', url: 'https://i.ibb.co/jknwpr9F/IMG-0717.jpg', category: 'still', title: 'Still IMG 0717' },
  { id: 'st-8', url: 'https://i.ibb.co/twdX7yqP/IMG-0711-1.jpg', category: 'still', title: 'Still IMG 0711' },
  { id: 'st-9', url: 'https://i.ibb.co/zT2X8KX2/IMG-0710.jpg', category: 'still', title: 'Still IMG 0710' },
  { id: 'st-10', url: 'https://i.ibb.co/Q3NyPnB8/IMG-0708.jpg', category: 'still', title: 'Still IMG 0708' },
  { id: 'st-11', url: 'https://i.ibb.co/kstNQFdN/IMG-0680.jpg', category: 'still', title: 'Still IMG 0680' },
  { id: 'st-12', url: 'https://i.ibb.co/W41QVzJV/IMG-0206.jpg', category: 'still', title: 'Still IMG 0206' },
  { id: 'st-13', url: 'https://i.ibb.co/yFkr90t4/IMG-0205.jpg', category: 'still', title: 'Still IMG 0205' },
  { id: 'st-14', url: 'https://i.ibb.co/twHrvF51/IMG-0157.jpg', category: 'still', title: 'Still IMG 0157' },
  { id: 'st-15', url: 'https://i.ibb.co/8nVJVx4d/MG-8787.jpg', category: 'still', title: 'Still MG 8787' },
  { id: 'st-16', url: 'https://i.ibb.co/zVyMrwQg/MG-8766.jpg', category: 'still', title: 'Still MG 8766' },
  { id: 'st-17', url: 'https://i.ibb.co/jZWhmtNN/MG-8736.jpg', category: 'still', title: 'Still MG 8736' },
  { id: 'st-18', url: 'https://i.ibb.co/svgMhnK3/MG-8734.jpg', category: 'still', title: 'Still MG 8734' },
  { id: 'st-19', url: 'https://i.ibb.co/PsgswP8H/MG-8721.jpg', category: 'still', title: 'Still MG 8721' },
  { id: 'st-20', url: 'https://i.ibb.co/S7DqMvjh/MG-8722.jpg', category: 'still', title: 'Still MG 8722' },
  { id: 'st-21', url: 'https://i.ibb.co/Y4gGg8gS/MG-7663.jpg', category: 'still', title: 'Still MG 7663' },
  { id: 'st-22', url: 'https://i.ibb.co/1x8p7Rg/MG-7660.jpg', category: 'still', title: 'Still MG 7660' },
  { id: 'st-23', url: 'https://i.ibb.co/Pv4BJ9pJ/MG-7656.jpg', category: 'still', title: 'Still MG 7656' },
  { id: 'st-24', url: 'https://i.ibb.co/DfFkXhw7/MG-7650.jpg', category: 'still', title: 'Still MG 7650' },
  { id: 'st-25', url: 'https://i.ibb.co/JRhSC5rT/MG-7512.jpg', category: 'still', title: 'Still MG 7512' },
  { id: 'st-26', url: 'https://i.ibb.co/n833HNFP/MG-7502.jpg', category: 'still', title: 'Still MG 7502' },
  { id: 'st-27', url: 'https://i.ibb.co/27MgXmpy/MG-7216.jpg', category: 'still', title: 'Still MG 7216' },
  { id: 'st-28', url: 'https://i.ibb.co/0R7yty86/MG-7212.jpg', category: 'still', title: 'Still MG 7212' },
  { id: 'st-29', url: 'https://i.ibb.co/QFXk5jCN/MG-7208.jpg', category: 'still', title: 'Still MG 7208' },
  { id: 'st-30', url: 'https://i.ibb.co/v4QThJT5/MG-7193.jpg', category: 'still', title: 'Still MG 7193' },
  { id: 'st-31', url: 'https://i.ibb.co/3mbd9x1L/MG-7179.jpg', category: 'still', title: 'Still MG 7179' },
  { id: 'st-32', url: 'https://i.ibb.co/qYmRxggr/MG-7176.jpg', category: 'still', title: 'Still MG 7176' },
  { id: 'st-33', url: 'https://i.ibb.co/JwxRj1JW/MG-6248.jpg', category: 'still', title: 'Still MG 6248' },
  { id: 'st-34', url: 'https://i.ibb.co/hJwJ8vxc/MG-7174.jpg', category: 'still', title: 'Still MG 7174' },
  { id: 'st-35', url: 'https://i.ibb.co/99YkG6bN/MG-6223.jpg', category: 'still', title: 'Still MG 6223' },
  { id: 'st-36', url: 'https://i.ibb.co/RkfYThR4/MG-6080.jpg', category: 'still', title: 'Still MG 6080' },
  { id: 'st-37', url: 'https://i.ibb.co/1fRgwq8w/MG-5958.jpg', category: 'still', title: 'Still MG 5958' },
  { id: 'st-38', url: 'https://i.ibb.co/bjtLNKkj/MG-5322.jpg', category: 'still', title: 'Still MG 5322' },

  // Ecommerce
  { id: 'ec-1', url: 'https://i.ibb.co/SDbtFY1w/IMG-4183.jpg', category: 'ecommerce', title: 'Ecommerce IMG 4183' },
  { id: 'ec-2', url: 'https://i.ibb.co/27TFkVdV/IMG-4182.jpg', category: 'ecommerce', title: 'Ecommerce IMG 4182' },
  { id: 'ec-3', url: 'https://i.ibb.co/chb7SGBM/IMG-4044.jpg', category: 'ecommerce', title: 'Ecommerce IMG 4044' },
];
